name: image-build
on:
  push:

jobs:
  image-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [linux/amd64, linux/arm64]
        target: [full, slim]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: ${{ matrix.arch }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            actions-runner-controlle:test-${{ matrix.target }}
