name: image-build
on:
  push:

jobs:
  image-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build
        uses: docker/bake-action@master
        with:
          push: false
          targets: artifact-all
          files: |
            docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - uses: actions/upload-artifact@v2
        with:
          name: action-runner-controller
          path: dist/**
