name: image-build
on:
  push:

jobs:
  bake:
    strategy:
      fail-fast: false
      matrix:
        bake-target: [full-amd64, slim-amd64, full-arm64, slim-arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build
        uses: docker/bake-action@master
        with:
          push: false
          targets: ${{ matrix.bake-target }}
          files: |
            docker-bake.hcl
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Remove json
        shell: bash
        run: find ./dist -name *.json* -type f -exec rm -f {} \;

      - uses: actions/upload-artifact@v2
        with:
          name: action-runner-controller
          path: dist/**
          retention-days: 1

  upload-artifact:
    name: Display results
    needs: bake
    runs-on: ubuntu-latest
    steps:
      - name: Download grep all artifact
        uses: actions/download-artifact@v2
        with:
          name: action-runner-controller
      - run: tree -alh
